#!/usr/bin/perl -w

# Generate usys.S, the stubs for syscalls.

print "# generated by usys.pl - do not edit\n";

print "#include \"kernel/syscall.h\"\n";

sub entry {
    my $prefix = "sys_";
    my $name = shift;
    if ($name eq "sbrk") {
	print ".global $prefix$name\n";
	print "$prefix$name:\n";
    } else {
	print ".global $name\n";
	print "$name:\n";
    }
    print " li a7, SYS_${name}\n";
    print " ecall\n";
    print " ret\n";
}
	
entry("fork");
entry("exit");
entry("wait");
entry("pipe");
entry("read");
entry("write");
entry("close");
entry("kill");
entry("exec");
entry("open");
entry("mknod");
entry("unlink");
entry("fstat");
entry("link");
entry("mkdir");
entry("chdir");
entry("dup");
entry("getpid");
entry("sbrk");
entry("sleep");
entry("pause");
entry("uptime");
entry("trace"); # CMPT 332 Nandish Jha NAJ474 11282001 2025 change
entry("mtx_create"); # CMPT 332 GROUP 01 Change, Fall 2025
entry("mtx_lock"); # CMPT 332 GROUP 01 Change, Fall 2025
entry("mtx_unlock"); # CMPT 332 GROUP 01 Change, Fall 2025
entry("get_num_free_pages"); # CMPT 332 GROUP 01 Change, Fall 2025 - A3
entry("setSchedAttr"); # CMPT 332 GROUP 01 Change, Fall 2025
entry("getSchedAttr"); # CMPT 332 GROUP 01 Change, Fall 202
entry("symlink"); # CMPT 332 NAJ474 11282001 Lab 8 - symlink